name: Generate snake animation

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate snake GIF
        uses: Platane/snk@v3
        with:
          github_user_name: Bonzokoles
          outputs: dist/github-snake.gif?color_snake=red&color_dots=%23090b10,%230d1017,%23151a24,%231c2333,%23242e42

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist